### ISSUE TITLE
when i use the cubemap maker, my character and camera freeze in place. when i click the move buttons or shoot, v1 does the animations in place, but no bullets are fired and I don't move. if i try to move my camera the lighting on my gun rotates, but not my actual camera. how do i fix this?

### ISSUE THREAD

**Issue by DaOverseer** [BobbyShmurner/CubemapMaker#1]

**Comment by BobbyShmurner** [comment]
Ah, sorry! I didn't get a notification about this for some reason!

Yeah I just tried it on the latest version and I see what you mean, I'll release a fix probably tomorrow because I'm very busy today

**Comment by BobbyShmurner** [comment]
Ok so...
It _isn't_ the next day, but it's been fixed now!

Sorry, I just completely forgot about this 😅
